[package]
name = "lunu-jobs"
version = "0.1.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
lunu-core.workspace = true
lunu-db.workspace = true
async-trait = "0.1"
chrono.workspace = true
tokio.workspace = true
tracing.workspace = true
