[package]
name = "lunu-api"
version = "0.1.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
lunu-core.workspace = true
lunu-config.workspace = true
lunu-db.workspace = true
lunu-i18n.workspace = true
lunu-integrations.workspace = true
actix-web.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
tracing.workspace = true
